#!/bin/bash
LC_ALL=C
LANG=C
RESPONSE=""
for i in /var/cache/obs/run/worker/*; do
	[ -e "$i/state" ] || continue
	NUM=${i##*/}
	read -r line < "$i"/state
	STATE=${line#*state=\"}
	STATE=${STATE%%\"*}
	RESPONSE+="${NUM} ${STATE}"$'\r\n'
done
printf "HTTP/1.0 200 OK\r\nContent-Length: %d\r\n\r\n" "${#RESPONSE}"
echo -n "$RESPONSE"
